import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [
        'getting-started/quick-start',
        'getting-started/introduction',
        'getting-started/getting-started',
        'getting-started/frequently-asked-questions',
        'getting-started/glossary',
      ],
    },
    {
      type: 'category',
      label: '📚 Core Concepts',
      items: [
        'core-concepts/what-is-mcp',
        'core-concepts/llm-basics',
        'core-concepts/provider-integrations',
        'core-concepts/technical-considerations',
        'core-concepts/user-stories',
      ],
    },
    {
      type: 'category',
      label: '🤖 AI Providers',
      items: [
        'ai-providers/index',
        'ai-providers/openai',
        'ai-providers/claude',
        'ai-providers/gemini',
        'ai-providers/llama',
        'ai-providers/mistral',
        'ai-providers/cohere',
        'ai-providers/qwen',
      ],
    },
    {
      type: 'category',
      label: '📖 Guides',
      items: [
        'guides/before-you-start',
        'guides/admin-ui',
        'guides/tool-management',
        'guides/logs',
        'guides/security',
        'guides/troubleshooting',
        'guides/ui-customization',
      ],
    },
    {
      type: 'category',
      label: '💡 Examples',
      items: [
        'examples/ecommerce-integration',
      ],
    },
    {
      type: 'category',
      label: '🔧 Advanced Topics',
      items: [
        'advanced-topics/advanced-usage',
        'advanced-topics/extensibility',
        'advanced-topics/migration-guide',
        'advanced-topics/provider-configuration',
        'advanced-topics/testing',
      ],
    },
    {
      type: 'category',
      label: '📋 Reference',
      items: [
        'reference/data-model',
        'reference/extensibility-hooks',
        'reference/plugin-architecture',
        'reference/supported-models',
        'reference/Roadmap',
      ],
    },
    'roadmap',
    'changelog',
    'contributing',
  ],
};

export default sidebars;
